# Working with CSV files!!!

### CSV (Comma-Separated Values) is one of the most commonly used file formats for storing and working with datasets in Machine Learning. 
<b>Example:</b>  
  
Name,Age,Marks,Result  
Ali,20,85,Pass  
Ahmed,21,72,Pass  
Sara,19,45,Fail  

In CSV files each row represents a record and commas act as columns .

___
### Importing Pandas Library

In [1]:
import pandas as pd

___
### Reading a Local/PC CSV File

In [4]:
df = pd.read_csv('aug_train.csv')

___
### Reading CSV File using URL:
<b>In order to read a csv file online, from a URL then we hace to :  </b>
1) First   
   import requests from io import StringIO
2) Then paste the url in the Qutations  
   url= ""
3) Place the header   
   headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
4) Then use the request module  
   req = requests.get(url, headers=headers)
5) Only for Reading Data, write :    
   data = StringIO(req.text)
6) Then read the data  
   pd.read_csv(data)

   You just have to copy this whole piece of data and use it by placinf only the url when you have to.

In [7]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

___
### There are two problems in this file 
1) Data is not saperated by commas.  
2) The first row itself becomes the Column/Feature names because there are no feature names.

We have to reolve both these issues.

### Before :

In [11]:
pd.read_csv('movie_titles_metadata.tsv')

    m0\t10 things i hate about you\t1999\t6.90\t62847\t['comedy' 'romance']
0    m1\t1492: conquest of paradise\t1992\t6.20\t10...
1    m2\t15 minutes\t2001\t6.10\t25854\t['action' '...
2    m3\t2001: a space odyssey\t1968\t8.40\t163227\...
3    m4\t48 hrs.\t1982\t6.90\t22289\t['action' 'com...
4    m5\tthe fifth element\t1997\t7.50\t133756\t['a...
..                                                 ...
611  m612\twatchmen\t2009\t7.80\t135229\t['action' ...
612  m613\txxx\t2002\t5.60\t53505\t['action' 'adven...
613  m614\tx-men\t2000\t7.40\t122149\t['action' 'sc...
614  m615\tyoung frankenstein\t1974\t8.00\t57618\t[...
615  m616\tzulu dawn\t1979\t6.40\t1911\t['action' '...

[616 rows x 1 columns]

### After :

1) It was a <b>TSV File</b> in which tabs are used for saperation therefor we used <b>sep</b> Parameter and pass the value as <b>/t</b>.    
2) There were no feature names so we added feature names using <b>names</b> parameter and give all the feature names in a list.

In [12]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genres'])

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

___
## Header Row 
 Incase if your feature names are apperaing as data row and you want them to make feature names then we will use <b>header</b> parameter.

 Same problem appears in this dataset and we will resolve it:

### Before:

In [15]:
pd.read_csv('test.csv')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
1,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

### After :

We used <b>header=1</b> which means make the row with index 1 as the header row.

In [19]:
pd.read_csv('test.csv',header=1)

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

___
### use_cols :

In order to use sepcific columns from the whole dataset we use the parameter <b>use_cols<b>

### Before :

In [21]:
pd.read_csv('aug_train.csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

### After :

Only the columns which we passed in the list are used and rest are dropped.

In [22]:
pd.read_csv('aug_train.csv',usecols=['enrollee_id','gender','education_level'])

       enrollee_id gender education_level
0             8949   Male        Graduate
1            29725   Male        Graduate
2            11561    NaN        Graduate
3            33241    NaN        Graduate
4              666   Male         Masters
...            ...    ...             ...
19153         7386   Male        Graduate
19154        31398   Male        Graduate
19155        24576   Male        Graduate
19156         5756   Male     High School
19157        23834    NaN  Primary School

[19158 rows x 3 columns]

___
### skip_rows:
If we want to skip one or more rows from the dataset than we use <b>skip_rows</b> parameter. In this case rows index will start from 1 not 0.

1) For removing the First n-rows we simply mention the value and the rows will be removed.  
Example :   
skip_rows=4  (This will remove the first 4 rows.)  

2) For removing certain rows we simply mention the rows value not index value and the rows will be removed.  
Example :   
skip_rows=[1,4]  (This will remove the first 1st and 4th row.)

3) For removing rows within a range we simply mention the range and the rows will be removed.  
Example :   
skip_rows=range(1,4)  (This will remove the rows from 1 to 3.)

### Before :

In [27]:
pd.read_csv('aug_train.csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

### After :

In [40]:
pd.read_csv('aug_train.csv',skiprows=range(1,4))

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
1,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
2,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
3,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
4,402,city_46,0.762,Male,Has relevent experience,no_enrollment,Graduate,STEM,13,<10,Pvt Ltd,>4,18,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19150,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19151,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19152,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19153,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19154,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

___
## dtype :

If we want to change the datatype of a feature/column then we use <b>dtype</b> and pass the column name with datatype in dictionary.

### Before : 
The datatype of last feature <b>target</b> is float .We will change it into integer.

In [49]:
pd.read_csv('aug_train.csv').info()

<class 'pandas.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  str
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  str
 4   relevent_experience     19158 non-null  str
 5   enrolled_university     18772 non-null  str
 6   education_level         18698 non-null  str
 7   major_discipline        16345 non-null  str
 8   experience              19093 non-null  str
 9   company_size            13220 non-null  str
 10  company_type            13018 non-null  str
 11  last_new_job            18735 non-null  str
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), str(10)
memory usage: 2.0 MB

### After :
The datatype is changed into int.

In [48]:
pd.read_csv('aug_train.csv',dtype={'target':int}).info()

<class 'pandas.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  str
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  str
 4   relevent_experience     19158 non-null  str
 5   enrolled_university     18772 non-null  str
 6   education_level         18698 non-null  str
 7   major_discipline        16345 non-null  str
 8   experience              19093 non-null  str
 9   company_size            13220 non-null  str
 10  company_type            13018 non-null  str
 11  last_new_job            18735 non-null  str
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int64
dtypes: float64(1), int64(3), str(10)
memory usage: 2.0 MB

___
## Handling Dates :
If there is a date column and that column is of string datatype so we can change its data type into date using the parameter <b>parse_dates</b>

### Before: 
We will convert the 3rd column date's datatype from string to date.

In [51]:
pd.read_csv('IPL Matches 2008-2020.csv').info()

<class 'pandas.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    str
 2   date             816 non-null    str
 3   player_of_match  812 non-null    str
 4   venue            816 non-null    str
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    str
 7   team2            816 non-null    str
 8   toss_winner      816 non-null    str
 9   toss_decision    816 non-null    str
 10  winner           812 non-null    str
 11  result           812 non-null    str
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    str
 14  method           19 non-null     str
 15  umpire1          816 non-null    str
 16  umpire2          816 non-null    str
dtypes: float64(1), int64(2), str(14)
memory usage: 108.5 KB

### After: 
Converted the Date column datatype from string to date.

In [50]:
pd.read_csv('IPL Matches 2008-2020.csv',parse_dates=['date']).info()

<class 'pandas.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    str
 2   date             816 non-null    datetime64[us]
 3   player_of_match  812 non-null    str
 4   venue            816 non-null    str
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    str
 7   team2            816 non-null    str
 8   toss_winner      816 non-null    str
 9   toss_decision    816 non-null    str
 10  winner           812 non-null    str
 11  result           812 non-null    str
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    str
 14  method           19 non-null     str
 15  umpire1          816 non-null    str
 16  umpire2          816 non-null    str
dtypes: datetime64[us](1), float64(1), int64(2), str(13)
memory usage: 108.5 KB

___
## converters :
converters are used to convert the values of a column when the CSV is being loaded.

1) We have used a saperate  function <b>rename</b> to rename the full names to abbreviations in the columns <b>team1</b> and used it in the converter parameter.

2) We have also used a condition for column <b>neutral_venue</b> to increase the value by 5.

### Before :

The values in column <b>team1</b> are <b>Royal Challengers Bangalore</b> and <b>Kings XI Punjab</b> we will conert them into <b>RCB</b> and <b>K XI P</b>.

We will also increase each value in the <b>neutral-value</b> column by <b>5</b>.

In [ ]:
pd.read_csv('IPL Matches 2008-2020.csv').head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

### After :

1) Rename is a simple python function we use it in the conerter parameter.

2) lambda represents each value in the column and we increment each value by 5.

In [59]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    elif name == "Kings XI Punjab":
        return "K XI P"
    else:
        return name

pd.read_csv('IPL Matches 2008-2020.csv',converters={'team1':rename,"neutral_venue":lambda x:int(x)+5}).head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,5,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",5,K XI P,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,5,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,5,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,5,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

___
## na_values :
If your dataset contain such values which are null but they are not markes as Nan e.g: '-' then you can make such values as Null values by using na_values parameter.

### Before :

We'll make the gender <b>Male</b> as NaN value just for learning.

In [60]:
pd.read_csv('aug_train.csv').head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

### After : 
All the Male values become NaN.

In [63]:
pd.read_csv('aug_train.csv',na_values=['Male']).head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

### This was all from Working with CSV Files !!!
___